syntax on
"set nu
set ruler
set autoindent
set cindent
set shiftwidth=4
set tabstop=4
set background=dark
set softtabstop=4
set t_Co=256
colorscheme molokai
let &termencoding=&encoding
set fileencodings=utf-8,gbk

"taglist-------------------
"let Tlist_Auto_Open=1
let Tlist_Use_Right_Window=1
let Tlist_Show_One_File=1
let TList_Use_Right_Window=1
let Tlist_WinHeigth=100
let Tlist_WinWidth=30
let Tlist_Exit_OnlyWindow=1
let TList_Ctags_Cmd='/root/Desktop/2016052401/tags'
noremap <F9> :TlistToggle<CR>


"NERDTree-------------------
"autocmd vimenter * NERDTree
map <F8> :NERDTreeToggle<CR>


"ycm "
let g:ycm_global_ycm_extra_conf='~/.vim/bundle/YouCompleteMe/.yct_extra_conf.py'
let g:ycm_confirm_extra_conf=0
let g:ycm_complete_in_comments=1
let g:ycm_collect_identifiers_from_tags_files=1
let g:ycm_min_num_of_chars_for_completion=1

"use color"
colorscheme molokai

set tags=/home/shaobo/Desktop/firmware-20161002(linux)/tags


set tags=/home/shaobo/Desktop/firmware-20161002(linux)/tags

set tags=/home/shaobo/Desktop/firmware-20161002(linux)/tags
